apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: pgswarm-system

patches:
  - path: pg-host-patch.yaml
    target:
      kind: Deployment
      name: pg-swarm-central
