apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-swarm-central
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          env:
            - name: PG_HOST
              value: postgres.pgswarm-system.svc.cluster.local
      containers:
        - name: central
          env:
            - name: LOG_LEVEL
              value: trace
            - name: PG_HOST
              value: postgres.pgswarm-system.svc.cluster.local
            - name: ENCRYPTION_KEY
              value: e639602b878c8faf08315e15b15392784446c043e6b2ef2fbb0f2835bfdf5cc9
