apiVersion: v1
kind: Service
metadata:
  name: pg-swarm-satellite
  namespace: pgswarm-system
  labels:
    app: pg-swarm-satellite
    app.kubernetes.io/part-of: pg-swarm
spec:
  type: ClusterIP
  selector:
    app: pg-swarm-satellite
  ports:
    - name: sidecar-grpc
      port: 9091
      targetPort: 9091
      protocol: TCP
