apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config
  namespace: pgswarm-system
  labels:
    app: pg-swarm-central
    app.kubernetes.io/part-of: pg-swarm
data:
  GRPC_ADDR: ":9090"
  HTTP_ADDR: ":8080"
