apiVersion: v1
kind: Service
metadata:
  name: pg-swarm-central-grpc
  namespace: pgswarm-system
  labels:
    app: pg-swarm-central
    app.kubernetes.io/part-of: pg-swarm
spec:
  type: ClusterIP
  selector:
    app: pg-swarm-central
  ports:
    - name: grpc
      port: 9090
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-swarm-central-http
  namespace: pgswarm-system
  labels:
    app: pg-swarm-central
    app.kubernetes.io/part-of: pg-swarm
spec:
  type: ClusterIP
  selector:
    app: pg-swarm-central
  ports:
    - name: http
      port: 8080
      targetPort: http
