package server

import (
	"context"
	"encoding/json"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	pgswarmv1 "github.com/pg-swarm/pg-swarm/api/gen/v1"
	"github.com/pg-swarm/pg-swarm/internal/central/store"
	"github.com/pg-swarm/pg-swarm/internal/shared/models"
	"github.com/rs/zerolog/log"
)

// emitCentralEvent creates and persists a central-only event. These events
// are generated by central itself (not received from a satellite) and are
// stored directly in the cluster_events table for audit and dashboard.
func emitCentralEvent(ctx context.Context, s store.Store, eventType string, satelliteID uuid.UUID, severity string, data map[string]string) {
	evt := &models.ClusterEvent{
		ID:          uuid.New(),
		EventType:   eventType,
		Severity:    severity,
		Source:      "central",
		SatelliteID: satelliteID,
		Data:        data,
		CreatedAt:   time.Now(),
	}

	if err := s.CreateClusterEvent(ctx, evt); err != nil {
		log.Error().Err(err).
			Str("event_type", eventType).
			Str("satellite_id", satelliteID.String()).
			Msg("failed to emit central event")
		return
	}

	log.Info().
		Str("event_type", eventType).
		Str("satellite_id", satelliteID.String()).
		Str("severity", severity).
		Msg("central event emitted")
}

// handleEvent is the unified event handler for all events received from
// satellites. It persists the event and dispatches side effects based on
// event type (dashboard updates, health storage, ops tracking, etc.).
func (s *GRPCServer) handleEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event) {
	evtType := evt.GetType()
	data := evt.GetData()

	log.Info().
		Str("satellite_id", satID.String()).
		Str("event_type", evtType).
		Str("cluster", evt.GetClusterName()).
		Str("pod", evt.GetPodName()).
		Str("severity", evt.GetSeverity()).
		Str("source", evt.GetSource()).
		Str("operation_id", evt.GetOperationId()).
		Msg("received event")

	// 1. Persist to cluster_events table
	ce := &models.ClusterEvent{
		EventType:   evtType,
		ClusterName: evt.GetClusterName(),
		Namespace:   evt.GetNamespace(),
		PodName:     evt.GetPodName(),
		Severity:    evt.GetSeverity(),
		Source:      evt.GetSource(),
		SatelliteID: satID,
		OperationID: evt.GetOperationId(),
		Data:        data,
	}
	if evt.GetId() != "" {
		if parsed, err := uuid.Parse(evt.GetId()); err == nil {
			ce.ID = parsed
		}
	}
	if evt.GetTimestamp() != nil {
		ce.CreatedAt = evt.GetTimestamp().AsTime()
	}
	if err := s.store.CreateClusterEvent(ctx, ce); err != nil {
		log.Error().Err(err).
			Str("satellite_id", satID.String()).
			Str("event_type", evtType).
			Msg("failed to store cluster event")
	}

	// 2. Dispatch side effects based on event type
	switch {
	case evtType == "health.report":
		s.handleHealthReportEvent(ctx, satID, evt)

	case evtType == "cluster.state_changed":
		s.handleStateChangedEvent(ctx, satID, evt, data)

	case evtType == "switchover.step":
		s.handleSwitchoverStepEvent(satID, evt, data)

	case evtType == "switchover.completed" || evtType == "switchover.failed":
		s.handleSwitchoverResultEvent(ctx, satID, evt, data)

	case evtType == "satellite.storage_classes_discovered":
		s.handleStorageClassesEvent(ctx, satID, data)

	case evtType == "database.created" || evtType == "database.create_failed":
		s.handleDatabaseEvent(ctx, satID, evt, data)

	case evtType == "config.applied" || evtType == "config.rejected":
		// Log only — no persistent side effect needed
		if evtType == "config.rejected" {
			log.Warn().
				Str("satellite_id", satID.String()).
				Str("cluster", evt.GetClusterName()).
				Str("error", data["error"]).
				Str("version", data["config_version"]).
				Msg("config rejected by satellite")
		}

	case evtType == "backup.status":
		s.handleBackupStatusEvent(ctx, satID, evt, data)

	case evtType == "restore.status":
		s.handleRestoreStatusEvent(ctx, satID, evt, data)
	}

	// 3. Notify dashboard for all events
	if s.wsHub != nil {
		s.wsHub.Notify()
	}
}

// handleHealthReportEvent replicates the old HealthReport handler's side effects:
// UpsertClusterHealth (with full instance data) + UpdateClusterConfigState.
func (s *GRPCServer) handleHealthReportEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event) {
	report := evt.GetHealthReport()
	if report == nil {
		// Fallback: no typed payload, use data map only
		state := mapStateString(evt.GetData()["state"])
		h := models.ClusterHealth{
			SatelliteID: satID,
			ClusterName: evt.GetClusterName(),
			State:       state,
			UpdatedAt:   time.Now(),
		}
		_ = s.store.UpsertClusterHealth(ctx, &h)
		_ = s.store.UpdateClusterConfigState(ctx, satID, evt.GetClusterName(), state)
		return
	}

	// Full report with instance details
	instances, err := protoInstancesToJSON(report.Instances)
	if err != nil {
		log.Error().Err(err).Str("satellite_id", satID.String()).Msg("failed to marshal instances from health event")
		return
	}

	state := protoStateToModel(report.State)
	h := models.ClusterHealth{
		SatelliteID: satID,
		ClusterName: report.ClusterName,
		State:       state,
		Instances:   instances,
		UpdatedAt:   time.Now(),
	}
	if err := s.store.UpsertClusterHealth(ctx, &h); err != nil {
		log.Error().Err(err).
			Str("satellite_id", satID.String()).
			Str("cluster", report.ClusterName).
			Msg("failed to upsert health from event")
		return
	}
	if err := s.store.UpdateClusterConfigState(ctx, satID, report.ClusterName, state); err != nil {
		log.Warn().Err(err).
			Str("cluster", report.ClusterName).
			Msg("failed to update cluster config state from event")
	}
	log.Debug().
		Str("satellite_id", satID.String()).
		Str("cluster", report.ClusterName).
		Str("state", string(state)).
		Int("instances", len(report.Instances)).
		Msg("health report event processed")
}

// handleStateChangedEvent replicates the old EventReport handler: creates
// an entry in the legacy events table for dashboard visibility.
func (s *GRPCServer) handleStateChangedEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event, data map[string]string) {
	msg := data["message"]
	if msg == "" {
		msg = "state changed: " + data["old_state"] + " -> " + data["new_state"]
	}
	legacyEvt := models.Event{
		ID:          uuid.New(),
		SatelliteID: satID,
		ClusterName: evt.GetClusterName(),
		Severity:    evt.GetSeverity(),
		Message:     msg,
		Source:      data["source"],
		CreatedAt:   time.Now(),
	}
	if legacyEvt.Source == "" {
		legacyEvt.Source = "health-monitor"
	}
	if err := s.store.CreateEvent(ctx, &legacyEvt); err != nil {
		log.Error().Err(err).Str("satellite_id", satID.String()).Msg("failed to create event from state change")
	}
}

// handleSwitchoverStepEvent replicates the old SwitchoverProgress handler:
// opsTracker update + WS broadcast.
func (s *GRPCServer) handleSwitchoverStepEvent(satID uuid.UUID, evt *pgswarmv1.Event, data map[string]string) {
	opID := evt.GetOperationId()
	step, _ := strconv.ParseInt(data["step"], 10, 32)
	stepName := data["step_name"]
	status := data["status"]
	targetPod := evt.GetPodName()
	errMsg := data["error"]
	ponr := data["point_of_no_return"] == "true"

	waitingForUser := false
	if s.opsTracker != nil {
		s.opsTracker.UpdateStep(opID, int32(step), stepName, status, targetPod, errMsg, ponr)
		if stepName == "find_primary" && status == "completed" && targetPod != "" {
			s.opsTracker.SetPrimaryPod(opID, targetPod)
		}
		// For interactive mode: park after each completed pre-PONR step so the user can confirm.
		if status == "completed" && !ponr {
			if op, ok := s.opsTracker.GetOp(opID); ok && op.Interactive {
				s.opsTracker.SetWaitingForUser(opID, int32(step))
				waitingForUser = true
			}
		}
	}
	if s.wsHub != nil {
		s.wsHub.BroadcastJSON("switchover_progress", map[string]interface{}{
			"operation_id":       opID,
			"cluster_name":       evt.GetClusterName(),
			"step":               step,
			"step_name":          stepName,
			"status":             status,
			"target_pod":         targetPod,
			"error_message":      errMsg,
			"point_of_no_return": ponr,
			"waiting_for_user":   waitingForUser,
		})
	}
}

// handleSwitchoverResultEvent replicates the old SwitchoverResult handler:
// opsTracker completion + WS broadcast + legacy event creation.
func (s *GRPCServer) handleSwitchoverResultEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event, data map[string]string) {
	opID := evt.GetOperationId()
	success := data["success"] == "true"
	errMsg := data["error"]

	severity := "info"
	msg := "planned switchover completed successfully"
	if !success {
		severity = "error"
		msg = "switchover failed: " + errMsg
	}

	_ = s.store.CreateEvent(ctx, &models.Event{
		ID: uuid.New(), SatelliteID: satID, ClusterName: evt.GetClusterName(),
		Severity: severity, Message: msg, Source: "switchover",
		CreatedAt: time.Now(),
	})

	if s.opsTracker != nil && opID != "" {
		s.opsTracker.Complete(opID, success, errMsg)
	}
	if s.wsHub != nil && opID != "" {
		s.wsHub.BroadcastJSON("switchover_complete", map[string]interface{}{
			"operation_id": opID,
			"cluster_name": evt.GetClusterName(),
			"success":      success,
			"error":        errMsg,
		})
	}
}

// handleStorageClassesEvent replicates the old StorageClassReport handler.
func (s *GRPCServer) handleStorageClassesEvent(ctx context.Context, satID uuid.UUID, data map[string]string) {
	countStr := data["count"]
	count, _ := strconv.Atoi(countStr)

	classes := make([]models.StorageClassInfo, 0, count)
	for i := 0; i < count; i++ {
		prefix := "sc_" + strconv.Itoa(i) + "_"
		name := data[prefix+"name"]
		if name == "" {
			continue
		}
		classes = append(classes, models.StorageClassInfo{
			Name:        name,
			Provisioner: data[prefix+"provisioner"],
			IsDefault:   data[prefix+"default"] == "true",
		})
	}

	if err := s.store.UpdateSatelliteStorageClasses(ctx, satID, classes); err != nil {
		log.Error().Err(err).Str("satellite_id", satID.String()).Msg("failed to store storage classes from event")
	} else {
		log.Info().Str("satellite_id", satID.String()).Int("count", len(classes)).Msg("storage classes updated from event")
	}
}

// handleDatabaseEvent processes database.created and database.create_failed events.
func (s *GRPCServer) handleDatabaseEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event, data map[string]string) {
	dbName := data["db_name"]
	if dbName == "" {
		return
	}
	status := "created"
	errMsg := ""
	if strings.HasSuffix(evt.GetType(), "_failed") {
		status = "failed"
		errMsg = data["error"]
	}
	log.Info().
		Str("satellite_id", satID.String()).
		Str("cluster", evt.GetClusterName()).
		Str("db_name", dbName).
		Str("status", status).
		Msg("database status from event")
	_ = errMsg // TODO: update cluster database status in store when wired
}

// handleBackupStatusEvent persists a backup status report from a sidecar.
func (s *GRPCServer) handleBackupStatusEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event, data map[string]string) {
	status := data["status"]
	backupType := data["backup_type"]
	sizeBytes, _ := strconv.ParseInt(data["size_bytes"], 10, 64)
	startedAt := time.Now()
	if evt.GetTimestamp() != nil {
		startedAt = evt.GetTimestamp().AsTime()
	}

	bi := &models.BackupInventory{
		ID:           uuid.New(),
		SatelliteID:  satID,
		ClusterName:  evt.GetClusterName(),
		BackupType:   backupType,
		Status:       status,
		StartedAt:    startedAt,
		SizeBytes:    sizeBytes,
		BackupPath:   data["backup_path"],
		PgVersion:    data["pg_version"],
		WalStartLSN:  data["wal_start_lsn"],
		WalEndLSN:    data["wal_end_lsn"],
		ErrorMessage: data["error_message"],
		CreatedAt:    time.Now(),
	}
	if status == "completed" || status == "failed" {
		now := time.Now()
		bi.CompletedAt = &now
	}
	if dbsJSON := data["databases"]; dbsJSON != "" {
		var dbs []string
		if json.Unmarshal([]byte(dbsJSON), &dbs) == nil {
			bi.Databases = dbs
		}
	}

	if err := s.store.CreateBackupInventory(ctx, bi); err != nil {
		log.Error().Err(err).Str("satellite_id", satID.String()).Str("cluster", evt.GetClusterName()).Msg("failed to store backup inventory")
	} else {
		log.Info().Str("satellite_id", satID.String()).Str("cluster", evt.GetClusterName()).
			Str("type", backupType).Str("status", status).Msg("backup status stored")
	}
}

// handleRestoreStatusEvent persists a restore status report from a sidecar.
func (s *GRPCServer) handleRestoreStatusEvent(ctx context.Context, satID uuid.UUID, evt *pgswarmv1.Event, data map[string]string) {
	restoreID := data["restore_id"]
	if restoreID == "" {
		log.Warn().Str("satellite_id", satID.String()).Msg("restore.status event missing restore_id")
		return
	}

	rid, err := uuid.Parse(restoreID)
	if err != nil {
		log.Warn().Str("restore_id", restoreID).Msg("restore.status event has invalid restore_id")
		return
	}

	ro, err := s.store.GetRestoreOperation(ctx, rid)
	if err != nil {
		// Record may not exist if the trigger was fired by an older central version
		// or the create failed transiently. Upsert a minimal record so the status
		// is at least visible in the list.
		log.Warn().Err(err).Str("restore_id", restoreID).Msg("restore operation not found — creating from status event")
		status := data["status"]
		now := time.Now()
		ro = &models.RestoreOperation{
			ID:             rid,
			SatelliteID:    satID,
			ClusterName:    evt.GetClusterName(),
			RestoreType:    data["restore_type"],
			TargetDatabase: data["restore_target_database"],
			Status:         status,
			ErrorMessage:   data["error_message"],
			CreatedAt:      now,
		}
		if status == "completed" || status == "failed" {
			ro.CompletedAt = &now
		}
		if err := s.store.CreateRestoreOperation(ctx, ro); err != nil {
			log.Error().Err(err).Str("restore_id", restoreID).Msg("failed to upsert restore operation from status event")
		}
		return
	}

	ro.Status = data["status"]
	ro.ErrorMessage = data["error_message"]
	if ro.Status == "completed" || ro.Status == "failed" {
		now := time.Now()
		ro.CompletedAt = &now
	}

	if err := s.store.UpdateRestoreOperation(ctx, ro); err != nil {
		log.Error().Err(err).Str("restore_id", restoreID).Msg("failed to update restore operation")
	} else {
		log.Info().Str("restore_id", restoreID).Str("status", ro.Status).Msg("restore status updated")
	}
}

// mapStateString converts a ClusterState proto enum string to the model state.
func mapStateString(s string) models.ClusterState {
	switch strings.ToUpper(s) {
	case "CLUSTER_STATE_CREATING", "CREATING":
		return models.ClusterStateCreating
	case "CLUSTER_STATE_RUNNING", "RUNNING":
		return models.ClusterStateRunning
	case "CLUSTER_STATE_DEGRADED", "DEGRADED":
		return models.ClusterStateDegraded
	case "CLUSTER_STATE_FAILED", "FAILED":
		return models.ClusterStateFailed
	case "CLUSTER_STATE_DELETING", "DELETING":
		return models.ClusterStateDeleting
	case "CLUSTER_STATE_PAUSED", "PAUSED":
		return models.ClusterStatePaused
	case "CLUSTER_STATE_UPDATING", "UPDATING":
		return models.ClusterStateUpdating
	default:
		return models.ClusterStateCreating
	}
}
